@LogiTrack_HostAddress = http://localhost:5112


########################################################################
# Auth / Security Endpoints
########################################################################


# REGISTER User without role
POST {{LogiTrack_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!"
}
#######


# LOGIN and retrieve JWT for User without role
POST {{LogiTrack_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!"
}
#######
# STORE returned JWT and RefreshToken
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjUzNzU4YzIyLWQ1YjEtNDAyMi04Nzk5LTdmOGQxZjYxNTQ3YyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlckBleGFtcGxlLmNvbSIsImV4cCI6MTc3MjEyODU3NSwiaXNzIjoiTG9naVRyYWNrQXBpIiwiYXVkIjoiTG9naVRyYWNrQ2xpZW50In0.FFEcTZeMmi8_XiviE7twimrqtcyl91Y0Y0zpPPfYp9M
@RefreshToken = J6PidUXWSTZ34Fjk%2FgBXgXXPBei9lo8JZQzuDRJZsjc%3D
#######


# LOGIN with invalid password (should fail)
POST {{LogiTrack_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "WrongPassword!"
}
#######


# READ all registered users (should fail - no Admin)
GET {{LogiTrack_HostAddress}}/api/auth/users
Authorization: Bearer {{AccessToken}}
#######


# REFRESH TOKEN for User without role (from HttpOnly cookie)
POST {{LogiTrack_HostAddress}}/api/auth/refresh-token
Cookie: refreshToken={{RefreshToken}}
Accept: application/json
#######


# LOGOUT User without role (should clear HttpOnly cookie)
POST {{LogiTrack_HostAddress}}/api/auth/logout
Cookie: refreshToken={{RefreshToken}}

#######




########################################################################
# Inventory endpoints
########################################################################


# READ all inventory items (should pass)
GET {{LogiTrack_HostAddress}}/api/inventory
Authorization: Bearer {{AccessToken}}
Accept: application/json
#######


# READ specific inventory item by ID (should pass)
GET {{LogiTrack_HostAddress}}/api/inventory/1
Authorization: Bearer {{AccessToken}}
Accept: application/json
#######


# CREATE a valid inventory item (should fail - no privileges)
POST {{LogiTrack_HostAddress}}/api/inventory
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Widget",
  "quantityInStock": 100,
  "price": 19.99,
  "location": "Warehouse A1"
}
#######


# UPDATE an existing inventory item (should fail - no privileges)
PUT {{LogiTrack_HostAddress}}/api/inventory/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Widget Pro",
  "quantityInStock": 150,
  "price": 24.99,
  "location": "A1"
}
#######


# DELETE inventory item (should fail - no privileges)
DELETE {{LogiTrack_HostAddress}}/api/inventory/1
Authorization: Bearer {{AccessToken}}
######




########################################################################
# Orders endpoints
########################################################################


# READ all orders (should pass)
GET {{LogiTrack_HostAddress}}/api/orders
Accept: application/json
Authorization: Bearer {{AccessToken}}
#######


# CREATE a new order with items (should fail - no privileges)
POST {{LogiTrack_HostAddress}}/api/orders
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "customerName": "Acme Corp",
  "orderItems": [
    {
      "inventoryItemId": 2,
      "quantityOrdered": 2
    },
    {
      "inventoryItemId": 3,
      "quantityOrdered": 1
    }
  ]
}
#######


# READ order by ID (should pass)
GET {{LogiTrack_HostAddress}}/api/orders/3
Accept: application/json
Authorization: Bearer {{AccessToken}}
#######


# ADD new InventoryItem to an existing order (should fail - no privileges)
POST {{LogiTrack_HostAddress}}/api/orders/1/items
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "inventoryItemId": 5,
  "quantityOrdered": 5
}
#######


# UPDATE quantity of an existing item, increasing by 3 (should fail - no privileges)
PATCH {{LogiTrack_HostAddress}}/api/orders/1/items/2?quantityChange=3
Authorization: Bearer {{AccessToken}}
#######


# UPDATE quantity of an existing item, decreasing by 1 (should fail - no privileges)
PATCH {{LogiTrack_HostAddress}}/api/orders/1/items/2?quantityChange=-1
Authorization: Bearer {{AccessToken}}
#######


# DELETE an item from a given order (should fail - no privileges)
DELETE {{LogiTrack_HostAddress}}/api/orders/1/items/3
Authorization: Bearer {{AccessToken}}
#######


# UPDATE order info (e.g., change CustomerName) (should fail - no privileges)
PATCH {{LogiTrack_HostAddress}}/api/orders/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "customerName": "Acme Corporation Ltd."
}
#######


# DELETE an existent order (should fail - no privileges)
DELETE {{LogiTrack_HostAddress}}/api/orders/1
Authorization: Bearer {{AccessToken}}
######