@E2_secure_api_with_jwt_HostAddress = http://localhost:5130

### login as user
POST {{E2_secure_api_with_jwt_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user123"
}

### Testing user endpoint with user token
GET {{E2_secure_api_with_jwt_HostAddress}}/values/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImp0aSI6IjNhZmU2MzY4LWFjZDMtNDQ1Ny1hZDU3LTRlZjViMDYxYjg5NiIsImV4cCI6MTc2ODc2OTAwOCwiaXNzIjoiU2VjdXJlQXBpIiwiYXVkIjoiU2VjdXJlQXBpVXNlcnMifQ.2kaMPB8XPbd7UbShslwrMs3w6boc3YE6m9rFM8La_Zk

### login as admin
POST {{E2_secure_api_with_jwt_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Testing admin endpoint with admin token
GET {{E2_secure_api_with_jwt_HostAddress}}/values/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiZGMyOTUzN2YtZmQyYi00ZTUzLWJiZGQtNjlmOTYyNGIyMTcyIiwiZXhwIjoxNzY4NzY5MDUyLCJpc3MiOiJTZWN1cmVBcGkiLCJhdWQiOiJTZWN1cmVBcGlVc2VycyJ9.LYckaMUhA1EU8g_IaOAp3PwGuTweSOx-wLbtgMwQVL0