@BaseAddress = http://localhost:5097
@CipherText = SznCZBO0b/kW2dd8C6Q+bUQTf9OsOCdA07IUY6VqtoQ=


### Encrypt Text
POST {{BaseAddress}}/api/crypto/encrypt
Content-Type: application/json

{
  "plainText": "hello world"
}

### Decrypt Text
POST {{BaseAddress}}/api/crypto/decrypt
Content-Type: application/json

{
  "cipherText": "{{CipherText}}"
}